# Generated by Django 3.1.4 on 2020-12-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
